### ISSUE TITLE
Timeout exception on get_file(file_id) after long delay between bot interactions #3830

### ISSUE THREAD

**Issue by awerks** [tdlib/telegram-bot-api#456]
Hello,

I've encountered an issue when using get_file(file_id) method in the python-telegram-bot library (v20.04). Whenever there is a long delay between bot interactions, I get a timeout error. However, on the second attempt, it works normally.

I'm running the bot in polling mode with local mode turned on. The bot itself and the local server are hosted on a cloud platform. 
Here are the logs of the error

```
Traceback to the issue
INFO - HKS (id: #######) has initalized a conversation.
﻿INFO - Downloading a file...
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/dist-packages/httpcore/_backends/anyio.py", line 34, in read
﻿return await self._stream.receive(max_bytes=max_bytes)
﻿File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 1203, in receive
﻿await self._protocol.read_event.wait()
﻿File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
﻿await futThe above exception was the direct cause of the following exception:
﻿Traceback (most recent call last):
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/request/_httpxrequest.py", line 216, in do_request
﻿res = await self._client.request(
﻿File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1530, in request
﻿return await self.send(request, auth=auth, follow_redirects=follow_redirects)
﻿File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1617, in send
﻿response = await self._send_handling_auth(
﻿File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1645, in _send_handling_auth
﻿response = await self._send_handling_redirects(
﻿File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1682, in _send_handling_redirects
﻿response = await self._send_single_request(request)
﻿File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1719, in _send_single_request
﻿response = await transport.handle_async_request(request)
﻿File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 352, in handle_async_request
﻿with map_httpcore_exceptions():
﻿File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
﻿self.gen.throw(typ, value, traceback)
﻿File "/usr/local/lib/python3.10/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
﻿raise mapped_exc(message) from exc
﻿httpx.ReadTimeout
﻿The above exception was the direct cause of the following exception:
﻿Traceback (most recent call last):
﻿File "/app/bot.py", line 866, in handle_video_or_document
﻿file = await context.bot.get_file(file_id)
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_extbot.py", line 1654, in get_file
﻿return await super().get_file(
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/_bot.py", line 388, in decorator
﻿result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/_bot.py", line 3047, in get_file
﻿result = await self._post(
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/_bot.py", line 476, in _post
﻿return await self._do_post(
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_extbot.py", line 332, in _do_post
﻿return await super()._do_post(
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/_bot.py", line 504, in _do_post
﻿return await request.post(
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py", line 168, in post
﻿result = await self._request_wrapper(
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py", line 288, in _request_wrapper
﻿raise exc
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py", line 278, in _request_wrapper
﻿code, payload = await self.do_request(
﻿File "/usr/local/lib/python3.10/dist-packages/telegram/request/_httpxrequest.py", line 233, in do_request
﻿raise TimedOut from err
﻿telegram.error.TimedOut: Timed out
INFO - HKS (id: #########) has initalized a conversation.
﻿INFO - Downloading a file...
﻿INFO - Downloaded succesfully...
```

###########

```
logger.info(f"{context.user_data['name']} (id: {context.user_data['user_id']}) has initalized a conversation.")
logger.info("Downloading a file...")
context.user_data["message"] = await update.message.reply_text(get(context, "downloading_video_text"))
if update.message.video:
    # The message is a video
    file_id = update.message.video.file_id
elif update.message.document:
    # The message is a document
    file_id = update.message.document.file_id

file = await context.bot.get_file(file_id)
logger.info("Downloaded succesfully...")
```

```
###########
application = Application.builder().token(TOKEN).base_url("http://127.0.0.1:8081/bot").base_file_url("http://127.0.0.1:8081/file/bot").local_mode(True).build()

application.run_polling(drop_pending_updates = True)

```

**Comment by awerks** [comment]
P.S This doesn't only happen after long delays. Sometimes, a request might succeed and then another one just 30 seconds later might fail

**Comment by levlam** [comment]
You can receive an error "﻿telegram.error.TimedOut" when a big file is being downloaded and request timeout set by the framework is too low. Or if the request is sent to a dead TCP connection, but this is unlikely for localhost connections.

The traces are printed if the Bot API server was suspended by OS for a long time, which can be related or not to the issue.

You can use options `--verbosity=4 --log=log.txt` to enable Bot API server log and write it to the `log.txt` file. You should be able to find exact cause in the Bot API server log when the issue happens next time.
