### ISSUE TITLE
Failed to send video using local api

### ISSUE THREAD

**Issue by Wenboli11** [tdlib/telegram-bot-api#475]
with open(f'{path}/{file_name}', 'rb') as video_file:
        if not video_file:
            print("没有这个文件")
            return
        async with bot:
            await bot.sendVideo(chat_id=chat_id, video=video_file, caption=caption,supports_streaming=True)

error :

Traceback (most recent call last):
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\anyio\_core\_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_backends\anyio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\anyio\_backends\_asyncio.py", line 1103, in receive
    await self._protocol.read_event.wait()
  File "C:\Users\23613\.conda\envs\tebot\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 203dde94c90

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_backends\anyio.py", line 32, in read
    with anyio.fail_after(timeout):
  File "C:\Users\23613\.conda\envs\tebot\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\anyio\_core\_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_async\connection_pool.py", line 262, in handle_async_request
    raise exc
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_async\connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_async\connection.py", line 96, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_async\http11.py", line 121, in handle_async_request
    raise exc
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_async\http11.py", line 99, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_async\http11.py", line 164, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_async\http11.py", line 200, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_backends\anyio.py", line 31, in read
    with map_exceptions(exc_map):
  File "C:\Users\23613\.conda\envs\tebot\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\request\_httpxrequest.py", line 219, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpx\_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpx\_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpx\_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpx\_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpx\_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpx\_transports\default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "C:\Users\23613\.conda\envs\tebot\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\23613\Desktop\autobot\mybot\main.py", line 92, in <module>
    asyncio.run(send_video(chat_id,row[1],row[9]))
  File "C:\Users\23613\.conda\envs\tebot\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\23613\Desktop\autobot\mybot\main.py", line 70, in send_video
    await bot.sendVideo(chat_id=chat_id, video=video_file, caption=caption,supports_streaming=True)
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\_bot.py", line 394, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\_bot.py", line 1527, in send_video
    return await self._send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\_bot.py", line 572, in _send_message
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\_bot.py", line 482, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\_bot.py", line 510, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\request\_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\request\_baserequest.py", line 288, in _request_wrapper
    raise exc
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\request\_baserequest.py", line 278, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\23613\.conda\envs\tebot\Lib\site-packages\telegram\request\_httpxrequest.py", line 236, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out

**Comment by levlam** [comment]
You seem to use too low timeout for HTTP requests.

**Comment by levlam** [comment]
write or read.
